version: '3.9'

services:
  db:
    container_name: pg_db
    image: postgres:alpine3.18
    environment:
      POSTGRES_DB: forum_app_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./pg-docker/postgres_data:/var/lib/postgresql/data
    networks:
      forum_net:
        ipv4_address: 10.5.0.3
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s

  backend:
    image: sanchine/forum_back
    container_name: forum_backend
    environment:
      PG_HOST: pg_db
      PG_LOGIN: admin
      PG_PASSWORD: admin
      PG_NAME: forum_app_db
      PORT: 5432
    networks:
      forum_net:
        ipv4_address: 10.5.0.4
    # healthcheck:
    #   test: ["CMD-SHELL", "curl", "127.0.0.1:3001/api/auth/test"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 3
    depends_on:
      db:
        condition: service_healthy

  nginx: 
    image: sanchine/forum_front
    container_name: forum_frontend
    ports:
      - "80:80"
    networks:
      forum_net:
        ipv4_address: 10.5.0.5
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      db:
        condition: service_healthy
      # backend:
      #   condition: service_healthy


  pgadmin:
    container_name: pg_admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      forum_net:
        ipv4_address: 10.5.0.6
  #   depends_on:
  #     db:
  #       condition: service_healthy

# volumes:
#   # - ./postgres_data:/var/lib/postgresql/data
#   forum_vol:
#     name: forum_vol

networks:
  forum_net:
    name: forum_net
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
